name: Ping URL at intervals during specific hours (JST)

on:
  schedule:
    # Runs every 20 minutes
    - cron: "*/20 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Check and ping URL
        run: |
          current_hour=$(TZ=Asia/Tokyo date +'%H')
          if [ "$current_hour" -ge 5 ] && [ "$current_hour" -lt 23 ]; then
            curl -s https://kokuraex.onrender.com/
          else
            echo "Current time is outside the allowed range (JST 5:00 - 23:00). Skipping URL ping."
          fi
